### ISSUE TITLE
Enrollment with mobile data

### ISSUE THREAD

**Issue by pierrenichele** [datalogic/aeqr#1]
Hello, this is not a problem but an idea
We sometimes enroll devices with mobile data because we lack Wifi on some buildings.

It could be usefull to have a checkbox to add this parameter :
"android.app.extra.PROVISIONING_USE_MOBILE_DATA":true

Thanks again for your tool that save us a lot of time.

**Comment by bronson-mock** [comment]
For Datalogic devices, you can configure an APN gateway for mobile networks under **Datalogic properties > Mobile network settings**
