### ISSUE TITLE
Can´t setup device

### ISSUE THREAD

**Issue by Marco3353** [datalogic/aeqr#2]
Hi, after creating a QR Code and trying to enroll my Scanner, I get an error message: 
"Can´t set up device. Can´t use the admin app. It´s missing components or corrupted. For help, contact your admin." 

In the past everything worked fine. I am trying to deploy them with Scan2Deploy. 
Hopefully this is the right topic here. 

BR, 
Marco

**Comment by bronson-mock** [comment]
Hi Marco,

Could you please provide the following information:

1. Device Model
2. Firmware version
3. Target EMM values
  a. Download and enrollment > DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION 
  b. Download and enrollment > DEVICE_ADMIN_SIGNATURE_CHECKSUM
